site_name: wom.py

plugins:
  - search
  - autorefs
  - mkdocstrings:
      custom_templates: docs/templates
      handlers:
        python:
          options:
            members_order: alphabetical
            # heading_level: 3
            docstring_style: google
            # docstring_style: numpy
            # docstring_section_style: list
            show_signature_annotations: true
            separate_signature: true
  - include-markdown

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - footnotes
  - pymdownx.tabbed:
      alternate_style: true

theme:
  name: material
  # custom_dir: docs/overrides

  palette:
    - scheme: slate
      primary: deep purple
      accent: purple
      toggle:
        icon: material/weather-night
        name: Switch to light mode

    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: light blue
      accent: purple
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

  font:
    text: Noto Sans
    code: Noto Sans Mono

  logo: wom-logo.png
  favicon: wom-ico.png

  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - content.tabs.link

  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/wom.py/
      name: PyPI
    - icon: fontawesome/brands/github
      link: https://github.com/Jonxslays/wom.py
      name: Source

copyright: Copyright &copy; 2023-present Jonxslays

repo_name: Jonxslays/wom.py
repo_url: https://github.com/Jonxslays/wom.py

nav:
  - "index.md"
  - "API reference":
    - "reference/client.md"
    - "reference/enums.md"
    - "reference/errors.md"
    - "reference/result.md"
    - "reference/routes.md"
    - "reference/serializer.md"
    - "reference/services.md"
    - "models":
      - "reference/models/base.md"
      - "reference/models/competitions.md"
      - "reference/models/deltas.md"
      - "reference/models/groups.md"
      - "reference/models/http.md"
      - "reference/models/names.md"
      - "reference/models/players.md"
      - "reference/models/records.md"
