site_name: wom.py

plugins:
  - search
  - autorefs
  - include-markdown
  - mkdocstrings:
      custom_templates: docs/templates
      handlers:
        python:
          options:
            members_order: source
            docstring_style: google
            show_signature_annotations: true
            separate_signature: true

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - footnotes
  - pymdownx.tabbed:
      alternate_style: true

watch:
  - wom

theme:
  name: material
  # custom_dir: docs/overrides

  palette:
    - scheme: slate
      primary: deep purple
      accent: purple
      toggle:
        icon: material/weather-night
        name: Switch to light mode

    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: light blue
      accent: purple
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

  font:
    text: Noto Sans
    code: Noto Sans Mono

  logo: wom-logo.svg
  favicon: wom-logo.png

  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - content.tabs.link

  icon:
    repo: fontawesome/brands/github

extra:
  version:
    provider: mike
    default: stable

  social:
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/wom.py
      name: PyPI
    - icon: fontawesome/brands/github
      link: https://github.com/Jonxslays/wom.py
      name: Source

copyright: Copyright &copy; 2023-present Jonxslays

repo_name: Jonxslays/wom.py
repo_url: https://github.com/Jonxslays/wom.py
site_url: https://jonxslays.github.io/wom.py

nav:
  - "index.md"
  - "Modules":
    - "reference/client.md"
    - "reference/enums.md"
    - "reference/errors.md"
    - "reference/result.md"
    - "reference/routes.md"
    - "reference/serializer.md"
    - "services":
      - "reference/services/base.md"
      - "reference/services/competitions.md"
      - "reference/services/deltas.md"
      - "reference/services/efficiency.md"
      - "reference/services/groups.md"
      - "reference/services/http.md"
      - "reference/services/names.md"
      - "reference/services/players.md"
      - "reference/services/records.md"
    - "models":
      - "reference/models/base.md"
      - "reference/models/competitions.md"
      - "reference/models/deltas.md"
      - "reference/models/groups.md"
      - "reference/models/http.md"
      - "reference/models/names.md"
      - "reference/models/players.md"
      - "reference/models/records.md"
  - "API Reference":
    - "reference/api.md"
