
name: Build docs

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install poetry
        uses: Gr1N/setup-poetry@v8

      - name: Build and deploy
        run: |
          pip install -U pip
          poetry install -q
          mkdocs gh-deploy --force
